# Frozen Lake (冰湖遊戲) 之值循環(Value Iteration)

In [10]:
# 載入相關套件
import numpy as np

# import gym
import gymnasium as gym

In [11]:
# 環境
env = gym.make('FrozenLake-v1') #注意要修改版本為 "FrozenLake-v1"
env.reset()

(0, {'prob': 1})

In [12]:
# 注意新版要定義 環境 space 和 行動 action 如下, 否則程式會出錯
nS = env.observation_space.n
nA = env.action_space.n

In [13]:
# 值循環函數
def value_iteration(env, theta=0.0001, discount_factor=0.9):
    # 計算行動值函數
    def one_step_lookahead(state, V):
        A = np.zeros(nA)
        for a in range(nA):
            for prob, next_state, reward, done in env.P[state][a]:
                A[a] += prob * (reward + discount_factor * V[next_state])
        return A

    # 狀態值函數初始化
    V = np.zeros(nS)
    while True:
        delta = 0
        # 更新每個狀態值的函數
        for s in range(nS):
            # 計算下一步的行動值函數
            A = one_step_lookahead(s, V)
            best_action_value = np.max(A)
            # 比較更新前後的差值，取最大值
            delta = max(delta, np.abs(best_action_value - V[s]))
            # 更新狀態值函數
            V[s] = best_action_value        
        # 若最大差值 < 門檻值，則停止評估
        if delta < theta:
            break

    # 一開始採隨機策略，往上/下/左/右走的機率(π)均等
    policy = np.zeros([nS, nA])
    for s in range(nS):
        # 計算下一步的行動值函數
        A = one_step_lookahead(s, V)
        # 選擇最佳行動
        best_action = np.argmax(A)
        # 永遠採取最佳行動
        policy[s, best_action] = 1.0
    
    return policy, V            

In [14]:
# 執行值循環
policy, v = value_iteration(env)

In [15]:
# 顯示結果
print("策略機率分配:")
print(policy)
print("")

print("4x4 策略機率分配 (0=up, 1=right, 2=down, 3=left):")
print(np.reshape(np.argmax(policy, axis=1), (int(nS ** 0.5), int(nS ** 0.5))))
print("")

print("4x4 狀態值函數:")
print(v.reshape((int(nS ** 0.5), int(nS ** 0.5))))

策略機率分配:
[[1. 0. 0. 0.]
 [0. 0. 0. 1.]
 [1. 0. 0. 0.]
 [0. 0. 0. 1.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 0. 1.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]]

4x4 策略機率分配 (0=up, 1=right, 2=down, 3=left):
[[0 3 0 3]
 [0 0 0 0]
 [3 1 0 0]
 [0 2 1 0]]

4x4 狀態值函數:
[[0.06848032 0.06111567 0.07422254 0.05560469]
 [0.09153995 0.         0.11212558 0.        ]
 [0.14522151 0.24737863 0.29954442 0.        ]
 [0.         0.37986011 0.63898452 0.        ]]


In [16]:
# 驗證答案是否正確
expected_v = np.array([ 0.06, 0.06, 0.07, 0.05, 0.09, 0, 0.11, 0, 0.14, 0.24, 0.29, 0, 0, 0.37, 0.63, 0])
np.testing.assert_array_almost_equal(v, expected_v, decimal=2)

## Frozen Lake (冰湖遊戲) 測試

In [17]:
# import gym
import gymnasium as gym

# 環境
env = gym.make('FrozenLake-v1')
env.reset()

# 執行策略循環
policy, v = value_iteration(env)

In [18]:
# 顯示結果
print("策略機率分配:")
print(policy)
print("")

print("4x4 策略機率分配 (0=up, 1=right, 2=down, 3=left):")
print(np.reshape(np.argmax(policy, axis=1), (int(nS ** 0.5), int(nS ** 0.5))))
print("")

print("4x4 狀態值函數:")
print(v.reshape((int(nS ** 0.5), int(nS ** 0.5))))

策略機率分配:
[[1. 0. 0. 0.]
 [0. 0. 0. 1.]
 [1. 0. 0. 0.]
 [0. 0. 0. 1.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 0. 1.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]]

4x4 策略機率分配 (0=up, 1=right, 2=down, 3=left):
[[0 3 0 3]
 [0 0 0 0]
 [3 1 0 0]
 [0 2 1 0]]

4x4 狀態值函數:
[[0.06848032 0.06111567 0.07422254 0.05560469]
 [0.09153995 0.         0.11212558 0.        ]
 [0.14522151 0.24737863 0.29954442 0.        ]
 [0.         0.37986011 0.63898452 0.        ]]
